# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/write_single_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QDialog

from settings import FUNCTION_LIST_WRITE


class Ui_WriteRegDialog_4(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.parent = parent

        self.setFixedSize(400, 250)
        self.setWindowTitle('Parameters')

        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setGeometry(QtCore.QRect(90, 180, 231, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_7 = QtWidgets.QLabel(self)
        self.label_7.setGeometry(QtCore.QRect(30, 150, 61, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.comboFunctionCode = QtWidgets.QComboBox(self)
        self.comboFunctionCode.setGeometry(QtCore.QRect(100, 150, 221, 22))
        self.comboFunctionCode.setObjectName("comboFunctionCode")
        self.SlaveID = QtWidgets.QTextEdit(self)
        self.SlaveID.setGeometry(QtCore.QRect(100, 20, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SlaveID.sizePolicy().hasHeightForWidth())
        self.SlaveID.setSizePolicy(sizePolicy)
        self.SlaveID.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SlaveID.setObjectName("SlaveID")
        self.Value = QtWidgets.QTextEdit(self)
        self.Value.setGeometry(QtCore.QRect(100, 80, 61, 21))
        self.Value.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Value.setObjectName("Value")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 21))
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.Address = QtWidgets.QTextEdit(self)
        self.Address.setGeometry(QtCore.QRect(100, 50, 61, 21))
        self.Address.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Address.setObjectName("Address")
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(30, 80, 61, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(30, 50, 61, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.checkBoxSigned = QtWidgets.QCheckBox(self)
        self.checkBoxSigned.setGeometry(QtCore.QRect(240, 80, 81, 20))
        self.checkBoxSigned.setObjectName("checkBoxSigned")
        self.label_8 = QtWidgets.QLabel(self)
        self.label_8.setGeometry(QtCore.QRect(30, 110, 61, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.Decimals = QtWidgets.QTextEdit(self)
        self.Decimals.setGeometry(QtCore.QRect(100, 110, 61, 21))
        self.Decimals.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Decimals.setObjectName("Decimals")

        self.retranslateUi(self)
        self.buttonBox.accepted.connect(self.accept)  # type: ignore
        self.buttonBox.rejected.connect(self.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(self)

        self.buttonBox.accepted.connect(self.set_write_params)
        self.buttonBox.rejected.connect(self.reject)
        self.buttonBox.accepted.connect(self.accept)

        self.Address.setText("1")
        self.SlaveID.setText(str(self.parent.slave4.params["slave_id"]))
        self.Value.setText("1")
        self.Decimals.setText("0")

        self.checkBoxSigned.setChecked(True)

        self.update_combobox()

    def update_combobox(self) -> None:
        """Обновление комбо-бокса"""
        self.parent.universal_list_update(
            FUNCTION_LIST_WRITE,
            self.comboFunctionCode)

        self.comboFunctionCode.setCurrentIndex(0)

    def set_write_params(self):
        self.parent.slave4.write_reg_params['slave_id'] = int(self.SlaveID.toPlainText())
        self.parent.slave4.write_reg_params['registeraddress'] = int(self.Address.toPlainText())
        self.parent.slave4.write_reg_params['value'] = float(self.Value.toPlainText())
        self.parent.slave4.write_reg_params['number_of_decimals'] = int(self.Decimals.toPlainText())
        self.parent.slave4.write_reg_params['signed'] = bool(self.checkBoxSigned.isChecked())

        selected_func = self.comboFunctionCode.itemText(
            self.comboFunctionCode.currentIndex()).split(" ")[0]
        self.parent.slave4.write_reg_params['functioncode'] = int(selected_func)

        self.write()

    def write(self):
        self.parent.write_register_4()

    def retranslateUi(self, WriteRegDialog):
        _translate = QtCore.QCoreApplication.translate
        WriteRegDialog.setWindowTitle(_translate("WriteRegDialog", "Write single register"))
        self.label_7.setText(_translate("WriteRegDialog", "Func Code"))
        self.label.setText(_translate("WriteRegDialog", "Slave ID"))
        self.label_6.setText(_translate("WriteRegDialog", "Value"))
        self.label_5.setText(_translate("WriteRegDialog", "Address"))
        self.label_8.setText(_translate("WriteRegDialog", "Decimals"))
        self.checkBoxSigned.setText(_translate("WriteRegDialog", "Signed"))
